// Generated by scripts/generate-world-maps.mjs. Do not edit by hand.
export const GENERATED_COUNTRY_ROWS = [
  {
    "code": "DZ",
    "name": "Algeria",
    "flag": "🇩🇿",
    "continentCode": "AF",
    "cityCode": "ALGIERS",
    "cityName": "Algiers",
    "longitude": 3,
    "latitude": 28
  },
  {
    "code": "AO",
    "name": "Angola",
    "flag": "🇦🇴",
    "continentCode": "AF",
    "cityCode": "LUANDA",
    "cityName": "Luanda",
    "longitude": 18.5,
    "latitude": -12.5
  },
  {
    "code": "BJ",
    "name": "Benin",
    "flag": "🇧🇯",
    "continentCode": "AF",
    "cityCode": "PORTO_NOVO",
    "cityName": "Porto-Novo",
    "longitude": 2.25,
    "latitude": 9.5
  },
  {
    "code": "BW",
    "name": "Botswana",
    "flag": "🇧🇼",
    "continentCode": "AF",
    "cityCode": "GABORONE",
    "cityName": "Gaborone",
    "longitude": 24,
    "latitude": -22
  },
  {
    "code": "BF",
    "name": "Burkina Faso",
    "flag": "🇧🇫",
    "continentCode": "AF",
    "cityCode": "OUAGADOUGOU",
    "cityName": "Ouagadougou",
    "longitude": -2,
    "latitude": 13
  },
  {
    "code": "BI",
    "name": "Burundi",
    "flag": "🇧🇮",
    "continentCode": "AF",
    "cityCode": "GITEGA",
    "cityName": "Gitega",
    "longitude": 30,
    "latitude": -3.5
  },
  {
    "code": "CM",
    "name": "Cameroon",
    "flag": "🇨🇲",
    "continentCode": "AF",
    "cityCode": "YAOUNDE",
    "cityName": "Yaoundé",
    "longitude": 12,
    "latitude": 6
  },
  {
    "code": "CV",
    "name": "Cape Verde",
    "flag": "🇨🇻",
    "continentCode": "AF",
    "cityCode": "PRAIA",
    "cityName": "Praia",
    "longitude": -24,
    "latitude": 16
  },
  {
    "code": "CF",
    "name": "Central African Republic",
    "flag": "🇨🇫",
    "continentCode": "AF",
    "cityCode": "BANGUI",
    "cityName": "Bangui",
    "longitude": 21,
    "latitude": 7
  },
  {
    "code": "TD",
    "name": "Chad",
    "flag": "🇹🇩",
    "continentCode": "AF",
    "cityCode": "N_DJAMENA",
    "cityName": "N'Djamena",
    "longitude": 19,
    "latitude": 15
  },
  {
    "code": "KM",
    "name": "Comoros",
    "flag": "🇰🇲",
    "continentCode": "AF",
    "cityCode": "MORONI",
    "cityName": "Moroni",
    "longitude": 44.25,
    "latitude": -12.16666666
  },
  {
    "code": "DJ",
    "name": "Djibouti",
    "flag": "🇩🇯",
    "continentCode": "AF",
    "cityCode": "DJIBOUTI",
    "cityName": "Djibouti",
    "longitude": 43,
    "latitude": 11.5
  },
  {
    "code": "CD",
    "name": "DR Congo",
    "flag": "🇨🇩",
    "continentCode": "AF",
    "cityCode": "KINSHASA",
    "cityName": "Kinshasa",
    "longitude": 25,
    "latitude": 0
  },
  {
    "code": "EG",
    "name": "Egypt",
    "flag": "🇪🇬",
    "continentCode": "AF",
    "cityCode": "CAIRO",
    "cityName": "Cairo",
    "longitude": 30,
    "latitude": 27
  },
  {
    "code": "GQ",
    "name": "Equatorial Guinea",
    "flag": "🇬🇶",
    "continentCode": "AF",
    "cityCode": "MALABO",
    "cityName": "Malabo",
    "longitude": 10,
    "latitude": 2
  },
  {
    "code": "ER",
    "name": "Eritrea",
    "flag": "🇪🇷",
    "continentCode": "AF",
    "cityCode": "ASMARA",
    "cityName": "Asmara",
    "longitude": 39,
    "latitude": 15
  },
  {
    "code": "SZ",
    "name": "Eswatini",
    "flag": "🇸🇿",
    "continentCode": "AF",
    "cityCode": "LOBAMBA",
    "cityName": "Lobamba",
    "longitude": 31.5,
    "latitude": -26.5
  },
  {
    "code": "ET",
    "name": "Ethiopia",
    "flag": "🇪🇹",
    "continentCode": "AF",
    "cityCode": "ADDIS_ABABA",
    "cityName": "Addis Ababa",
    "longitude": 38,
    "latitude": 8
  },
  {
    "code": "GA",
    "name": "Gabon",
    "flag": "🇬🇦",
    "continentCode": "AF",
    "cityCode": "LIBREVILLE",
    "cityName": "Libreville",
    "longitude": 11.75,
    "latitude": -1
  },
  {
    "code": "GM",
    "name": "Gambia",
    "flag": "🇬🇲",
    "continentCode": "AF",
    "cityCode": "BANJUL",
    "cityName": "Banjul",
    "longitude": -16.56666666,
    "latitude": 13.46666666
  },
  {
    "code": "GH",
    "name": "Ghana",
    "flag": "🇬🇭",
    "continentCode": "AF",
    "cityCode": "ACCRA",
    "cityName": "Accra",
    "longitude": -2,
    "latitude": 8
  },
  {
    "code": "GN",
    "name": "Guinea",
    "flag": "🇬🇳",
    "continentCode": "AF",
    "cityCode": "CONAKRY",
    "cityName": "Conakry",
    "longitude": -10,
    "latitude": 11
  },
  {
    "code": "GW",
    "name": "Guinea-Bissau",
    "flag": "🇬🇼",
    "continentCode": "AF",
    "cityCode": "BISSAU",
    "cityName": "Bissau",
    "longitude": -15,
    "latitude": 12
  },
  {
    "code": "CI",
    "name": "Ivory Coast",
    "flag": "🇨🇮",
    "continentCode": "AF",
    "cityCode": "YAMOUSSOUKRO",
    "cityName": "Yamoussoukro",
    "longitude": -5,
    "latitude": 8
  },
  {
    "code": "KE",
    "name": "Kenya",
    "flag": "🇰🇪",
    "continentCode": "AF",
    "cityCode": "NAIROBI",
    "cityName": "Nairobi",
    "longitude": 38,
    "latitude": 1
  },
  {
    "code": "LS",
    "name": "Lesotho",
    "flag": "🇱🇸",
    "continentCode": "AF",
    "cityCode": "MASERU",
    "cityName": "Maseru",
    "longitude": 28.5,
    "latitude": -29.5
  },
  {
    "code": "LR",
    "name": "Liberia",
    "flag": "🇱🇷",
    "continentCode": "AF",
    "cityCode": "MONROVIA",
    "cityName": "Monrovia",
    "longitude": -9.5,
    "latitude": 6.5
  },
  {
    "code": "LY",
    "name": "Libya",
    "flag": "🇱🇾",
    "continentCode": "AF",
    "cityCode": "TRIPOLI",
    "cityName": "Tripoli",
    "longitude": 17,
    "latitude": 25
  },
  {
    "code": "MG",
    "name": "Madagascar",
    "flag": "🇲🇬",
    "continentCode": "AF",
    "cityCode": "ANTANANARIVO",
    "cityName": "Antananarivo",
    "longitude": 47,
    "latitude": -20
  },
  {
    "code": "MW",
    "name": "Malawi",
    "flag": "🇲🇼",
    "continentCode": "AF",
    "cityCode": "LILONGWE",
    "cityName": "Lilongwe",
    "longitude": 34,
    "latitude": -13.5
  },
  {
    "code": "ML",
    "name": "Mali",
    "flag": "🇲🇱",
    "continentCode": "AF",
    "cityCode": "BAMAKO",
    "cityName": "Bamako",
    "longitude": -4,
    "latitude": 17
  },
  {
    "code": "MR",
    "name": "Mauritania",
    "flag": "🇲🇷",
    "continentCode": "AF",
    "cityCode": "NOUAKCHOTT",
    "cityName": "Nouakchott",
    "longitude": -12,
    "latitude": 20
  },
  {
    "code": "MU",
    "name": "Mauritius",
    "flag": "🇲🇺",
    "continentCode": "AF",
    "cityCode": "PORT_LOUIS",
    "cityName": "Port Louis",
    "longitude": 57.55,
    "latitude": -20.28333333
  },
  {
    "code": "MA",
    "name": "Morocco",
    "flag": "🇲🇦",
    "continentCode": "AF",
    "cityCode": "RABAT",
    "cityName": "Rabat",
    "longitude": -5,
    "latitude": 32
  },
  {
    "code": "MZ",
    "name": "Mozambique",
    "flag": "🇲🇿",
    "continentCode": "AF",
    "cityCode": "MAPUTO",
    "cityName": "Maputo",
    "longitude": 35,
    "latitude": -18.25
  },
  {
    "code": "NA",
    "name": "Namibia",
    "flag": "🇳🇦",
    "continentCode": "AF",
    "cityCode": "WINDHOEK",
    "cityName": "Windhoek",
    "longitude": 17,
    "latitude": -22
  },
  {
    "code": "NE",
    "name": "Niger",
    "flag": "🇳🇪",
    "continentCode": "AF",
    "cityCode": "NIAMEY",
    "cityName": "Niamey",
    "longitude": 8,
    "latitude": 16
  },
  {
    "code": "NG",
    "name": "Nigeria",
    "flag": "🇳🇬",
    "continentCode": "AF",
    "cityCode": "ABUJA",
    "cityName": "Abuja",
    "longitude": 8,
    "latitude": 10
  },
  {
    "code": "CG",
    "name": "Republic of the Congo",
    "flag": "🇨🇬",
    "continentCode": "AF",
    "cityCode": "BRAZZAVILLE",
    "cityName": "Brazzaville",
    "longitude": 15,
    "latitude": -1
  },
  {
    "code": "RW",
    "name": "Rwanda",
    "flag": "🇷🇼",
    "continentCode": "AF",
    "cityCode": "KIGALI",
    "cityName": "Kigali",
    "longitude": 30,
    "latitude": -2
  },
  {
    "code": "ST",
    "name": "São Tomé and Príncipe",
    "flag": "🇸🇹",
    "continentCode": "AF",
    "cityCode": "SAO_TOME",
    "cityName": "São Tomé",
    "longitude": 7,
    "latitude": 1
  },
  {
    "code": "SN",
    "name": "Senegal",
    "flag": "🇸🇳",
    "continentCode": "AF",
    "cityCode": "DAKAR",
    "cityName": "Dakar",
    "longitude": -14,
    "latitude": 14
  },
  {
    "code": "SC",
    "name": "Seychelles",
    "flag": "🇸🇨",
    "continentCode": "AF",
    "cityCode": "VICTORIA",
    "cityName": "Victoria",
    "longitude": 55.66666666,
    "latitude": -4.58333333
  },
  {
    "code": "SL",
    "name": "Sierra Leone",
    "flag": "🇸🇱",
    "continentCode": "AF",
    "cityCode": "FREETOWN",
    "cityName": "Freetown",
    "longitude": -11.5,
    "latitude": 8.5
  },
  {
    "code": "SO",
    "name": "Somalia",
    "flag": "🇸🇴",
    "continentCode": "AF",
    "cityCode": "MOGADISHU",
    "cityName": "Mogadishu",
    "longitude": 49,
    "latitude": 10
  },
  {
    "code": "ZA",
    "name": "South Africa",
    "flag": "🇿🇦",
    "continentCode": "AF",
    "cityCode": "PRETORIA",
    "cityName": "Pretoria",
    "longitude": 24,
    "latitude": -29
  },
  {
    "code": "SS",
    "name": "South Sudan",
    "flag": "🇸🇸",
    "continentCode": "AF",
    "cityCode": "JUBA",
    "cityName": "Juba",
    "longitude": 30,
    "latitude": 7
  },
  {
    "code": "SD",
    "name": "Sudan",
    "flag": "🇸🇩",
    "continentCode": "AF",
    "cityCode": "KHARTOUM",
    "cityName": "Khartoum",
    "longitude": 30,
    "latitude": 15
  },
  {
    "code": "TZ",
    "name": "Tanzania",
    "flag": "🇹🇿",
    "continentCode": "AF",
    "cityCode": "DODOMA",
    "cityName": "Dodoma",
    "longitude": 35,
    "latitude": -6
  },
  {
    "code": "TG",
    "name": "Togo",
    "flag": "🇹🇬",
    "continentCode": "AF",
    "cityCode": "LOME",
    "cityName": "Lomé",
    "longitude": 1.16666666,
    "latitude": 8
  },
  {
    "code": "TN",
    "name": "Tunisia",
    "flag": "🇹🇳",
    "continentCode": "AF",
    "cityCode": "TUNIS",
    "cityName": "Tunis",
    "longitude": 9,
    "latitude": 34
  },
  {
    "code": "UG",
    "name": "Uganda",
    "flag": "🇺🇬",
    "continentCode": "AF",
    "cityCode": "KAMPALA",
    "cityName": "Kampala",
    "longitude": 32,
    "latitude": 1
  },
  {
    "code": "ZM",
    "name": "Zambia",
    "flag": "🇿🇲",
    "continentCode": "AF",
    "cityCode": "LUSAKA",
    "cityName": "Lusaka",
    "longitude": 30,
    "latitude": -15
  },
  {
    "code": "ZW",
    "name": "Zimbabwe",
    "flag": "🇿🇼",
    "continentCode": "AF",
    "cityCode": "HARARE",
    "cityName": "Harare",
    "longitude": 30,
    "latitude": -20
  },
  {
    "code": "AQ",
    "name": "Antarctica",
    "flag": "🇦🇶",
    "continentCode": "AN",
    "cityCode": "RESEARCH_STATIONS",
    "cityName": "Research Stations",
    "longitude": 0,
    "latitude": -75
  },
  {
    "code": "AL",
    "name": "Albania",
    "flag": "🇦🇱",
    "continentCode": "EU",
    "cityCode": "TIRANA",
    "cityName": "Tirana",
    "longitude": 20,
    "latitude": 41
  },
  {
    "code": "AD",
    "name": "Andorra",
    "flag": "🇦🇩",
    "continentCode": "EU",
    "cityCode": "ANDORRA_LA_VELLA",
    "cityName": "Andorra la Vella",
    "longitude": 1.5,
    "latitude": 42.5
  },
  {
    "code": "AT",
    "name": "Austria",
    "flag": "🇦🇹",
    "continentCode": "EU",
    "cityCode": "VIENNA",
    "cityName": "Vienna",
    "longitude": 13.33333333,
    "latitude": 47.33333333
  },
  {
    "code": "BY",
    "name": "Belarus",
    "flag": "🇧🇾",
    "continentCode": "EU",
    "cityCode": "MINSK",
    "cityName": "Minsk",
    "longitude": 28,
    "latitude": 53
  },
  {
    "code": "BE",
    "name": "Belgium",
    "flag": "🇧🇪",
    "continentCode": "EU",
    "cityCode": "BRUSSELS",
    "cityName": "Brussels",
    "longitude": 4,
    "latitude": 50.83333333
  },
  {
    "code": "BA",
    "name": "Bosnia and Herzegovina",
    "flag": "🇧🇦",
    "continentCode": "EU",
    "cityCode": "SARAJEVO",
    "cityName": "Sarajevo",
    "longitude": 18,
    "latitude": 44
  },
  {
    "code": "BG",
    "name": "Bulgaria",
    "flag": "🇧🇬",
    "continentCode": "EU",
    "cityCode": "SOFIA",
    "cityName": "Sofia",
    "longitude": 25,
    "latitude": 43
  },
  {
    "code": "HR",
    "name": "Croatia",
    "flag": "🇭🇷",
    "continentCode": "EU",
    "cityCode": "ZAGREB",
    "cityName": "Zagreb",
    "longitude": 15.5,
    "latitude": 45.16666666
  },
  {
    "code": "CZ",
    "name": "Czechia",
    "flag": "🇨🇿",
    "continentCode": "EU",
    "cityCode": "PRAGUE",
    "cityName": "Prague",
    "longitude": 15.5,
    "latitude": 49.75
  },
  {
    "code": "DK",
    "name": "Denmark",
    "flag": "🇩🇰",
    "continentCode": "EU",
    "cityCode": "COPENHAGEN",
    "cityName": "Copenhagen",
    "longitude": 10,
    "latitude": 56
  },
  {
    "code": "EE",
    "name": "Estonia",
    "flag": "🇪🇪",
    "continentCode": "EU",
    "cityCode": "TALLINN",
    "cityName": "Tallinn",
    "longitude": 26,
    "latitude": 59
  },
  {
    "code": "FI",
    "name": "Finland",
    "flag": "🇫🇮",
    "continentCode": "EU",
    "cityCode": "HELSINKI",
    "cityName": "Helsinki",
    "longitude": 26,
    "latitude": 64
  },
  {
    "code": "FR",
    "name": "France",
    "flag": "🇫🇷",
    "continentCode": "EU",
    "cityCode": "PARIS",
    "cityName": "Paris",
    "longitude": 2,
    "latitude": 46
  },
  {
    "code": "DE",
    "name": "Germany",
    "flag": "🇩🇪",
    "continentCode": "EU",
    "cityCode": "BERLIN",
    "cityName": "Berlin",
    "longitude": 9,
    "latitude": 51
  },
  {
    "code": "GR",
    "name": "Greece",
    "flag": "🇬🇷",
    "continentCode": "EU",
    "cityCode": "ATHENS",
    "cityName": "Athens",
    "longitude": 22,
    "latitude": 39
  },
  {
    "code": "HU",
    "name": "Hungary",
    "flag": "🇭🇺",
    "continentCode": "EU",
    "cityCode": "BUDAPEST",
    "cityName": "Budapest",
    "longitude": 20,
    "latitude": 47
  },
  {
    "code": "IS",
    "name": "Iceland",
    "flag": "🇮🇸",
    "continentCode": "EU",
    "cityCode": "REYKJAVIK",
    "cityName": "Reykjavik",
    "longitude": -18,
    "latitude": 65
  },
  {
    "code": "IE",
    "name": "Ireland",
    "flag": "🇮🇪",
    "continentCode": "EU",
    "cityCode": "DUBLIN",
    "cityName": "Dublin",
    "longitude": -8,
    "latitude": 53
  },
  {
    "code": "IT",
    "name": "Italy",
    "flag": "🇮🇹",
    "continentCode": "EU",
    "cityCode": "ROME",
    "cityName": "Rome",
    "longitude": 12.83333333,
    "latitude": 42.83333333
  },
  {
    "code": "LV",
    "name": "Latvia",
    "flag": "🇱🇻",
    "continentCode": "EU",
    "cityCode": "RIGA",
    "cityName": "Riga",
    "longitude": 25,
    "latitude": 57
  },
  {
    "code": "LI",
    "name": "Liechtenstein",
    "flag": "🇱🇮",
    "continentCode": "EU",
    "cityCode": "VADUZ",
    "cityName": "Vaduz",
    "longitude": 9.53333333,
    "latitude": 47.26666666
  },
  {
    "code": "LT",
    "name": "Lithuania",
    "flag": "🇱🇹",
    "continentCode": "EU",
    "cityCode": "VILNIUS",
    "cityName": "Vilnius",
    "longitude": 24,
    "latitude": 56
  },
  {
    "code": "LU",
    "name": "Luxembourg",
    "flag": "🇱🇺",
    "continentCode": "EU",
    "cityCode": "LUXEMBOURG",
    "cityName": "Luxembourg",
    "longitude": 6.16666666,
    "latitude": 49.75
  },
  {
    "code": "MT",
    "name": "Malta",
    "flag": "🇲🇹",
    "continentCode": "EU",
    "cityCode": "VALLETTA",
    "cityName": "Valletta",
    "longitude": 14.58333333,
    "latitude": 35.83333333
  },
  {
    "code": "MD",
    "name": "Moldova",
    "flag": "🇲🇩",
    "continentCode": "EU",
    "cityCode": "CHISINAU",
    "cityName": "Chișinău",
    "longitude": 29,
    "latitude": 47
  },
  {
    "code": "MC",
    "name": "Monaco",
    "flag": "🇲🇨",
    "continentCode": "EU",
    "cityCode": "MONACO",
    "cityName": "Monaco",
    "longitude": 7.4,
    "latitude": 43.73333333
  },
  {
    "code": "ME",
    "name": "Montenegro",
    "flag": "🇲🇪",
    "continentCode": "EU",
    "cityCode": "PODGORICA",
    "cityName": "Podgorica",
    "longitude": 19.3,
    "latitude": 42.5
  },
  {
    "code": "NL",
    "name": "Netherlands",
    "flag": "🇳🇱",
    "continentCode": "EU",
    "cityCode": "AMSTERDAM",
    "cityName": "Amsterdam",
    "longitude": 5.75,
    "latitude": 52.5
  },
  {
    "code": "MK",
    "name": "North Macedonia",
    "flag": "🇲🇰",
    "continentCode": "EU",
    "cityCode": "SKOPJE",
    "cityName": "Skopje",
    "longitude": 22,
    "latitude": 41.83333333
  },
  {
    "code": "NO",
    "name": "Norway",
    "flag": "🇳🇴",
    "continentCode": "EU",
    "cityCode": "OSLO",
    "cityName": "Oslo",
    "longitude": 10,
    "latitude": 62
  },
  {
    "code": "PL",
    "name": "Poland",
    "flag": "🇵🇱",
    "continentCode": "EU",
    "cityCode": "WARSAW",
    "cityName": "Warsaw",
    "longitude": 20,
    "latitude": 52
  },
  {
    "code": "PT",
    "name": "Portugal",
    "flag": "🇵🇹",
    "continentCode": "EU",
    "cityCode": "LISBON",
    "cityName": "Lisbon",
    "longitude": -8,
    "latitude": 39.5
  },
  {
    "code": "RO",
    "name": "Romania",
    "flag": "🇷🇴",
    "continentCode": "EU",
    "cityCode": "BUCHAREST",
    "cityName": "Bucharest",
    "longitude": 25,
    "latitude": 46
  },
  {
    "code": "RU",
    "name": "Russia",
    "flag": "🇷🇺",
    "continentCode": "EU",
    "cityCode": "MOSCOW",
    "cityName": "Moscow",
    "longitude": 100,
    "latitude": 60
  },
  {
    "code": "SM",
    "name": "San Marino",
    "flag": "🇸🇲",
    "continentCode": "EU",
    "cityCode": "CITY_OF_SAN_MARINO",
    "cityName": "City of San Marino",
    "longitude": 12.41666666,
    "latitude": 43.76666666
  },
  {
    "code": "RS",
    "name": "Serbia",
    "flag": "🇷🇸",
    "continentCode": "EU",
    "cityCode": "BELGRADE",
    "cityName": "Belgrade",
    "longitude": 21,
    "latitude": 44
  },
  {
    "code": "SK",
    "name": "Slovakia",
    "flag": "🇸🇰",
    "continentCode": "EU",
    "cityCode": "BRATISLAVA",
    "cityName": "Bratislava",
    "longitude": 19.5,
    "latitude": 48.66666666
  },
  {
    "code": "SI",
    "name": "Slovenia",
    "flag": "🇸🇮",
    "continentCode": "EU",
    "cityCode": "LJUBLJANA",
    "cityName": "Ljubljana",
    "longitude": 14.81666666,
    "latitude": 46.11666666
  },
  {
    "code": "ES",
    "name": "Spain",
    "flag": "🇪🇸",
    "continentCode": "EU",
    "cityCode": "MADRID",
    "cityName": "Madrid",
    "longitude": -4,
    "latitude": 40
  },
  {
    "code": "SE",
    "name": "Sweden",
    "flag": "🇸🇪",
    "continentCode": "EU",
    "cityCode": "STOCKHOLM",
    "cityName": "Stockholm",
    "longitude": 15,
    "latitude": 62
  },
  {
    "code": "CH",
    "name": "Switzerland",
    "flag": "🇨🇭",
    "continentCode": "EU",
    "cityCode": "BERN",
    "cityName": "Bern",
    "longitude": 8,
    "latitude": 47
  },
  {
    "code": "UA",
    "name": "Ukraine",
    "flag": "🇺🇦",
    "continentCode": "EU",
    "cityCode": "KYIV",
    "cityName": "Kyiv",
    "longitude": 32,
    "latitude": 49
  },
  {
    "code": "GB",
    "name": "United Kingdom",
    "flag": "🇬🇧",
    "continentCode": "EU",
    "cityCode": "LONDON",
    "cityName": "London",
    "longitude": -2,
    "latitude": 54
  },
  {
    "code": "VA",
    "name": "Vatican City",
    "flag": "🇻🇦",
    "continentCode": "EU",
    "cityCode": "VATICAN_CITY",
    "cityName": "Vatican City",
    "longitude": 12.45,
    "latitude": 41.9
  },
  {
    "code": "AG",
    "name": "Antigua and Barbuda",
    "flag": "🇦🇬",
    "continentCode": "NA",
    "cityCode": "SAINT_JOHN_S",
    "cityName": "Saint John's",
    "longitude": -61.8,
    "latitude": 17.05
  },
  {
    "code": "BS",
    "name": "Bahamas",
    "flag": "🇧🇸",
    "continentCode": "NA",
    "cityCode": "NASSAU",
    "cityName": "Nassau",
    "longitude": -76,
    "latitude": 24.25
  },
  {
    "code": "BB",
    "name": "Barbados",
    "flag": "🇧🇧",
    "continentCode": "NA",
    "cityCode": "BRIDGETOWN",
    "cityName": "Bridgetown",
    "longitude": -59.53333333,
    "latitude": 13.16666666
  },
  {
    "code": "BZ",
    "name": "Belize",
    "flag": "🇧🇿",
    "continentCode": "NA",
    "cityCode": "BELMOPAN",
    "cityName": "Belmopan",
    "longitude": -88.75,
    "latitude": 17.25
  },
  {
    "code": "CA",
    "name": "Canada",
    "flag": "🇨🇦",
    "continentCode": "NA",
    "cityCode": "OTTAWA",
    "cityName": "Ottawa",
    "longitude": -95,
    "latitude": 60
  },
  {
    "code": "CR",
    "name": "Costa Rica",
    "flag": "🇨🇷",
    "continentCode": "NA",
    "cityCode": "SAN_JOSE",
    "cityName": "San José",
    "longitude": -84,
    "latitude": 10
  },
  {
    "code": "CU",
    "name": "Cuba",
    "flag": "🇨🇺",
    "continentCode": "NA",
    "cityCode": "HAVANA",
    "cityName": "Havana",
    "longitude": -80,
    "latitude": 21.5
  },
  {
    "code": "DM",
    "name": "Dominica",
    "flag": "🇩🇲",
    "continentCode": "NA",
    "cityCode": "ROSEAU",
    "cityName": "Roseau",
    "longitude": -61.33333333,
    "latitude": 15.41666666
  },
  {
    "code": "DO",
    "name": "Dominican Republic",
    "flag": "🇩🇴",
    "continentCode": "NA",
    "cityCode": "SANTO_DOMINGO",
    "cityName": "Santo Domingo",
    "longitude": -70.66666666,
    "latitude": 19
  },
  {
    "code": "SV",
    "name": "El Salvador",
    "flag": "🇸🇻",
    "continentCode": "NA",
    "cityCode": "SAN_SALVADOR",
    "cityName": "San Salvador",
    "longitude": -88.91666666,
    "latitude": 13.83333333
  },
  {
    "code": "GD",
    "name": "Grenada",
    "flag": "🇬🇩",
    "continentCode": "NA",
    "cityCode": "ST_GEORGE_S",
    "cityName": "St. George's",
    "longitude": -61.66666666,
    "latitude": 12.11666666
  },
  {
    "code": "GT",
    "name": "Guatemala",
    "flag": "🇬🇹",
    "continentCode": "NA",
    "cityCode": "GUATEMALA_CITY",
    "cityName": "Guatemala City",
    "longitude": -90.25,
    "latitude": 15.5
  },
  {
    "code": "HT",
    "name": "Haiti",
    "flag": "🇭🇹",
    "continentCode": "NA",
    "cityCode": "PORT_AU_PRINCE",
    "cityName": "Port-au-Prince",
    "longitude": -72.41666666,
    "latitude": 19
  },
  {
    "code": "HN",
    "name": "Honduras",
    "flag": "🇭🇳",
    "continentCode": "NA",
    "cityCode": "TEGUCIGALPA",
    "cityName": "Tegucigalpa",
    "longitude": -86.5,
    "latitude": 15
  },
  {
    "code": "JM",
    "name": "Jamaica",
    "flag": "🇯🇲",
    "continentCode": "NA",
    "cityCode": "KINGSTON",
    "cityName": "Kingston",
    "longitude": -77.5,
    "latitude": 18.25
  },
  {
    "code": "MX",
    "name": "Mexico",
    "flag": "🇲🇽",
    "continentCode": "NA",
    "cityCode": "MEXICO_CITY",
    "cityName": "Mexico City",
    "longitude": -102,
    "latitude": 23
  },
  {
    "code": "NI",
    "name": "Nicaragua",
    "flag": "🇳🇮",
    "continentCode": "NA",
    "cityCode": "MANAGUA",
    "cityName": "Managua",
    "longitude": -85,
    "latitude": 13
  },
  {
    "code": "PA",
    "name": "Panama",
    "flag": "🇵🇦",
    "continentCode": "NA",
    "cityCode": "PANAMA_CITY",
    "cityName": "Panama City",
    "longitude": -80,
    "latitude": 9
  },
  {
    "code": "KN",
    "name": "Saint Kitts and Nevis",
    "flag": "🇰🇳",
    "continentCode": "NA",
    "cityCode": "BASSETERRE",
    "cityName": "Basseterre",
    "longitude": -62.75,
    "latitude": 17.33333333
  },
  {
    "code": "LC",
    "name": "Saint Lucia",
    "flag": "🇱🇨",
    "continentCode": "NA",
    "cityCode": "CASTRIES",
    "cityName": "Castries",
    "longitude": -60.96666666,
    "latitude": 13.88333333
  },
  {
    "code": "VC",
    "name": "Saint Vincent and the Grenadines",
    "flag": "🇻🇨",
    "continentCode": "NA",
    "cityCode": "KINGSTOWN",
    "cityName": "Kingstown",
    "longitude": -61.2,
    "latitude": 13.25
  },
  {
    "code": "TT",
    "name": "Trinidad and Tobago",
    "flag": "🇹🇹",
    "continentCode": "NA",
    "cityCode": "PORT_OF_SPAIN",
    "cityName": "Port of Spain",
    "longitude": -61,
    "latitude": 11
  },
  {
    "code": "US",
    "name": "United States",
    "flag": "🇺🇸",
    "continentCode": "NA",
    "cityCode": "WASHINGTON_D_C",
    "cityName": "Washington D.C.",
    "longitude": -97,
    "latitude": 38
  },
  {
    "code": "AU",
    "name": "Australia",
    "flag": "🇦🇺",
    "continentCode": "OC",
    "cityCode": "CANBERRA",
    "cityName": "Canberra",
    "longitude": 133,
    "latitude": -27
  },
  {
    "code": "FJ",
    "name": "Fiji",
    "flag": "🇫🇯",
    "continentCode": "OC",
    "cityCode": "SUVA",
    "cityName": "Suva",
    "longitude": 175,
    "latitude": -18
  },
  {
    "code": "KI",
    "name": "Kiribati",
    "flag": "🇰🇮",
    "continentCode": "OC",
    "cityCode": "SOUTH_TARAWA",
    "cityName": "South Tarawa",
    "longitude": 173,
    "latitude": 1.41666666
  },
  {
    "code": "MH",
    "name": "Marshall Islands",
    "flag": "🇲🇭",
    "continentCode": "OC",
    "cityCode": "MAJURO",
    "cityName": "Majuro",
    "longitude": 168,
    "latitude": 9
  },
  {
    "code": "FM",
    "name": "Micronesia",
    "flag": "🇫🇲",
    "continentCode": "OC",
    "cityCode": "PALIKIR",
    "cityName": "Palikir",
    "longitude": 158.25,
    "latitude": 6.91666666
  },
  {
    "code": "NR",
    "name": "Nauru",
    "flag": "🇳🇷",
    "continentCode": "OC",
    "cityCode": "YAREN",
    "cityName": "Yaren",
    "longitude": 166.91666666,
    "latitude": -0.53333333
  },
  {
    "code": "NZ",
    "name": "New Zealand",
    "flag": "🇳🇿",
    "continentCode": "OC",
    "cityCode": "WELLINGTON",
    "cityName": "Wellington",
    "longitude": 174,
    "latitude": -41
  },
  {
    "code": "PW",
    "name": "Palau",
    "flag": "🇵🇼",
    "continentCode": "OC",
    "cityCode": "NGERULMUD",
    "cityName": "Ngerulmud",
    "longitude": 134.5,
    "latitude": 7.5
  },
  {
    "code": "PG",
    "name": "Papua New Guinea",
    "flag": "🇵🇬",
    "continentCode": "OC",
    "cityCode": "PORT_MORESBY",
    "cityName": "Port Moresby",
    "longitude": 147,
    "latitude": -6
  },
  {
    "code": "WS",
    "name": "Samoa",
    "flag": "🇼🇸",
    "continentCode": "OC",
    "cityCode": "APIA",
    "cityName": "Apia",
    "longitude": -172.33333333,
    "latitude": -13.58333333
  },
  {
    "code": "SB",
    "name": "Solomon Islands",
    "flag": "🇸🇧",
    "continentCode": "OC",
    "cityCode": "HONIARA",
    "cityName": "Honiara",
    "longitude": 159,
    "latitude": -8
  },
  {
    "code": "TO",
    "name": "Tonga",
    "flag": "🇹🇴",
    "continentCode": "OC",
    "cityCode": "NUKU_ALOFA",
    "cityName": "Nuku'alofa",
    "longitude": -175,
    "latitude": -20
  },
  {
    "code": "TV",
    "name": "Tuvalu",
    "flag": "🇹🇻",
    "continentCode": "OC",
    "cityCode": "FUNAFUTI",
    "cityName": "Funafuti",
    "longitude": 178,
    "latitude": -8
  },
  {
    "code": "VU",
    "name": "Vanuatu",
    "flag": "🇻🇺",
    "continentCode": "OC",
    "cityCode": "PORT_VILA",
    "cityName": "Port Vila",
    "longitude": 167,
    "latitude": -16
  },
  {
    "code": "AR",
    "name": "Argentina",
    "flag": "🇦🇷",
    "continentCode": "SA",
    "cityCode": "BUENOS_AIRES",
    "cityName": "Buenos Aires",
    "longitude": -64,
    "latitude": -34
  },
  {
    "code": "BO",
    "name": "Bolivia",
    "flag": "🇧🇴",
    "continentCode": "SA",
    "cityCode": "SUCRE",
    "cityName": "Sucre",
    "longitude": -65,
    "latitude": -17
  },
  {
    "code": "BR",
    "name": "Brazil",
    "flag": "🇧🇷",
    "continentCode": "SA",
    "cityCode": "BRASILIA",
    "cityName": "Brasília",
    "longitude": -55,
    "latitude": -10
  },
  {
    "code": "CL",
    "name": "Chile",
    "flag": "🇨🇱",
    "continentCode": "SA",
    "cityCode": "SANTIAGO",
    "cityName": "Santiago",
    "longitude": -71,
    "latitude": -30
  },
  {
    "code": "CO",
    "name": "Colombia",
    "flag": "🇨🇴",
    "continentCode": "SA",
    "cityCode": "BOGOTA",
    "cityName": "Bogotá",
    "longitude": -72,
    "latitude": 4
  },
  {
    "code": "EC",
    "name": "Ecuador",
    "flag": "🇪🇨",
    "continentCode": "SA",
    "cityCode": "QUITO",
    "cityName": "Quito",
    "longitude": -77.5,
    "latitude": -2
  },
  {
    "code": "GY",
    "name": "Guyana",
    "flag": "🇬🇾",
    "continentCode": "SA",
    "cityCode": "GEORGETOWN",
    "cityName": "Georgetown",
    "longitude": -59,
    "latitude": 5
  },
  {
    "code": "PY",
    "name": "Paraguay",
    "flag": "🇵🇾",
    "continentCode": "SA",
    "cityCode": "ASUNCION",
    "cityName": "Asunción",
    "longitude": -58,
    "latitude": -23
  },
  {
    "code": "PE",
    "name": "Peru",
    "flag": "🇵🇪",
    "continentCode": "SA",
    "cityCode": "LIMA",
    "cityName": "Lima",
    "longitude": -76,
    "latitude": -10
  },
  {
    "code": "SR",
    "name": "Suriname",
    "flag": "🇸🇷",
    "continentCode": "SA",
    "cityCode": "PARAMARIBO",
    "cityName": "Paramaribo",
    "longitude": -56,
    "latitude": 4
  },
  {
    "code": "UY",
    "name": "Uruguay",
    "flag": "🇺🇾",
    "continentCode": "SA",
    "cityCode": "MONTEVIDEO",
    "cityName": "Montevideo",
    "longitude": -56,
    "latitude": -33
  },
  {
    "code": "VE",
    "name": "Venezuela",
    "flag": "🇻🇪",
    "continentCode": "SA",
    "cityCode": "CARACAS",
    "cityName": "Caracas",
    "longitude": -66,
    "latitude": 8
  }
] as const;
